project:
  type: website
  output-dir: _site

website:
  title: "Catalog Format"
  description: "You (probably) don't need a vector database"
  repo-url: https://github.com/hushh-labs/hushh-vibe-catalog
  page-navigation: true
  favicon: "figures/logo.svg"
  navbar:
    pinned: true
    logo: "figures/logo.svg"
    logo-alt: "hushh-home"
    search: true
    left:
      - text: "Reference"
        file: reference/index.qmd
      - text: "Changelog"
        file: changelog.md
      - text: "Learn more"
        menu:
          - text: "Introductory Article"
            href: https://hushh-labs.github.io/hushh-labs-blog/posts/you_dont_need_a_vector_database.html
            target: _blank
          - text: "Hushh Catalog Trusted Python Deployment"
            href: https://hushh-labs.github.io/hushh-labs-blog/posts/python_engineering.html
            target: _blank
    right:
      - icon: github
        href: https://github.com/hushh-labs/hushh-vibe-catalog
        aria-label: hushh vibe catalog github

  sidebar:
    - id: reference
      contents: "_sidebar.yml"

quartodoc:
  style: pkgdown
  package: hushh 
  renderer:
    style: markdown
    display_name: relative
  sidebar: "_sidebar.yml"
  sections:
    - title: Catalog
      desc: ""
      contents:
        - name: catalog 
          children: linked
        - catalog.Product
        - catalog.Catalog
        - catalog.Brand

    - title: HCF
      desc: "Autogenerated Python Clients from Flatbuffer Schemas"
      contents:
        - hcf


metadata-files:
  - _sidebar.yml

profile:
  default: latest

format:
  html:
    theme:
      - pulse
