project:
  type: website
  output-dir: docs


execute:
  freeze: auto

# tell quarto to read the generated sidebar
# metadata-files:
#   - _sidebar.yml

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: hushh

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Catalog
      desc: Catalog functions
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - hcf
        - hcf.Catalog
        - hcf.Product
        - hcf.Category
        - hcf.Embedding
        - hcf.Vibe
        - catalog

