# catalog { #hushh.catalog }

`catalog`



## Classes

| Name | Description |
| --- | --- |
| [Catalog](#hushh.catalog.Catalog) | Represents a catalog of products. |
| [Category](#hushh.catalog.Category) | Represents a category of products. |
| [Embedding](#hushh.catalog.Embedding) | Represents an embedding. |
| [Product](#hushh.catalog.Product) | Represents a product. |
| [Vibe](#hushh.catalog.Vibe) | Represents a vibe. |

### Catalog { #hushh.catalog.Catalog }

`catalog.Catalog(self, description, products=None)`

Represents a catalog of products.

#### Attributes

| Name        | Type                    | Description                           |
|-------------|-------------------------|---------------------------------------|
| id          | str                     | The unique identifier of the catalog. |
| version     | str                     | The version of the catalog.           |
| description | str                     | The description of the catalog.       |
| products    | list\[Product\] or None | The list of products in the catalog.  |

### Category { #hushh.catalog.Category }

`catalog.Category(self, description, url, embeddings=None)`

Represents a category of products.

#### Attributes

| Name        | Type                      | Description                                          |
|-------------|---------------------------|------------------------------------------------------|
| description | str                       | The description of the category.                     |
| url         | str                       | The URL of the category.                             |
| embeddings  | list\[Embedding\] or None | The list of embeddings associated with the category. |

### Embedding { #hushh.catalog.Embedding }

`catalog.Embedding(self, v=None)`

Represents an embedding.

#### Attributes

| Name   | Type                  | Description           |
|--------|-----------------------|-----------------------|
| v      | list\[float\] or None | The vector embedding. |

### Product { #hushh.catalog.Product }

`catalog.Product(self, description, url, categories=None, vibes=None)`

Represents a product.

#### Attributes

| Name        | Type                     | Description                                    |
|-------------|--------------------------|------------------------------------------------|
| id          | str                      | The unique identifier of the product.          |
| description | str                      | The description of the product.                |
| url         | str                      | The URL of the product.                        |
| categories  | list\[Category\] or None | The list of categories the product belongs to. |
| vibes       | list\[Vibe\] or None     | The list of vibes associated with the product. |

### Vibe { #hushh.catalog.Vibe }

`catalog.Vibe(self, description, imageBase64, url, embeddings=None)`

Represents a vibe.

#### Attributes

| Name        | Type                      | Description                                      |
|-------------|---------------------------|--------------------------------------------------|
| id          | str                       | The unique identifier of the vibe.               |
| description | str                       | The description of the vibe.                     |
| imageBase64 | str or None               | The base64 encoded image of the vibe.            |
| url         | str                       | The URL of the vibe.                             |
| embeddings  | list\[Embedding\] or None | The list of embeddings associated with the vibe. |