# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hushh

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ProductCharacterization(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProductCharacterization()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProductCharacterization(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProductCharacterization
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProductCharacterization
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProductCharacterization
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProductCharacterization
    def Url(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProductCharacterization
    def ProductIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # ProductCharacterization
    def ProductIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ProductCharacterization
    def ProductIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def ProductCharacterizationStart(builder):
    builder.StartObject(4)

def Start(builder):
    ProductCharacterizationStart(builder)

def ProductCharacterizationAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    ProductCharacterizationAddId(builder, id)

def ProductCharacterizationAddDescription(builder, description):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def AddDescription(builder, description):
    ProductCharacterizationAddDescription(builder, description)

def ProductCharacterizationAddUrl(builder, url):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)

def AddUrl(builder, url):
    ProductCharacterizationAddUrl(builder, url)

def ProductCharacterizationAddProductIds(builder, productIds):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(productIds), 0)

def AddProductIds(builder, productIds):
    ProductCharacterizationAddProductIds(builder, productIds)

def ProductCharacterizationStartProductIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartProductIdsVector(builder, numElems: int) -> int:
    return ProductCharacterizationStartProductIdsVector(builder, numElems)

def ProductCharacterizationEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProductCharacterizationEnd(builder)
