# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hcf

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from hushh.hcf.Vibe import Vibe
from typing import Optional
np = import_numpy()

class Category(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Category()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCategory(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Category
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Category
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Category
    def Description(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Category
    def Url(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Category
    def Vibes(self, j: int) -> Optional[Vibe]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Vibe()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Category
    def VibesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Category
    def VibesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def CategoryStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    CategoryStart(builder)

def CategoryAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    CategoryAddId(builder, id)

def CategoryAddDescription(builder: flatbuffers.Builder, description: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def AddDescription(builder: flatbuffers.Builder, description: int):
    CategoryAddDescription(builder, description)

def CategoryAddUrl(builder: flatbuffers.Builder, url: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)

def AddUrl(builder: flatbuffers.Builder, url: int):
    CategoryAddUrl(builder, url)

def CategoryAddVibes(builder: flatbuffers.Builder, vibes: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(vibes), 0)

def AddVibes(builder: flatbuffers.Builder, vibes: int):
    CategoryAddVibes(builder, vibes)

def CategoryStartVibesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartVibesVector(builder, numElems: int) -> int:
    return CategoryStartVibesVector(builder, numElems)

def CategoryEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CategoryEnd(builder)

import hushh.hcf.Vibe
try:
    from typing import List
except:
    pass

class CategoryT(object):

    # CategoryT
    def __init__(self):
        self.id = None  # type: str
        self.description = None  # type: str
        self.url = None  # type: str
        self.vibes = None  # type: List[hushh.hcf.Vibe.VibeT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        category = Category()
        category.Init(buf, pos)
        return cls.InitFromObj(category)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, category):
        x = CategoryT()
        x._UnPack(category)
        return x

    # CategoryT
    def _UnPack(self, category):
        if category is None:
            return
        self.id = category.Id()
        self.description = category.Description()
        self.url = category.Url()
        if not category.VibesIsNone():
            self.vibes = []
            for i in range(category.VibesLength()):
                if category.Vibes(i) is None:
                    self.vibes.append(None)
                else:
                    vibe_ = hushh.hcf.Vibe.VibeT.InitFromObj(category.Vibes(i))
                    self.vibes.append(vibe_)

    # CategoryT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.description is not None:
            description = builder.CreateString(self.description)
        if self.url is not None:
            url = builder.CreateString(self.url)
        if self.vibes is not None:
            vibeslist = []
            for i in range(len(self.vibes)):
                vibeslist.append(self.vibes[i].Pack(builder))
            CategoryStartVibesVector(builder, len(self.vibes))
            for i in reversed(range(len(self.vibes))):
                builder.PrependUOffsetTRelative(vibeslist[i])
            vibes = builder.EndVector()
        CategoryStart(builder)
        if self.id is not None:
            CategoryAddId(builder, id)
        if self.description is not None:
            CategoryAddDescription(builder, description)
        if self.url is not None:
            CategoryAddUrl(builder, url)
        if self.vibes is not None:
            CategoryAddVibes(builder, vibes)
        category = CategoryEnd(builder)
        return category
