# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hcf

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from hushh.hcf.Brand import Brand
from typing import Optional
np = import_numpy()

class Product(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Product()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProduct(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Product
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Product
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Product
    def Description(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Product
    def Url(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Product
    def Brand(self) -> Optional[Brand]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Brand()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ProductStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    ProductStart(builder)

def ProductAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    ProductAddId(builder, id)

def ProductAddDescription(builder: flatbuffers.Builder, description: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def AddDescription(builder: flatbuffers.Builder, description: int):
    ProductAddDescription(builder, description)

def ProductAddUrl(builder: flatbuffers.Builder, url: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)

def AddUrl(builder: flatbuffers.Builder, url: int):
    ProductAddUrl(builder, url)

def ProductAddBrand(builder: flatbuffers.Builder, brand: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(brand), 0)

def AddBrand(builder: flatbuffers.Builder, brand: int):
    ProductAddBrand(builder, brand)

def ProductEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ProductEnd(builder)

import hushh.hcf.Brand
try:
    from typing import Optional
except:
    pass

class ProductT(object):

    # ProductT
    def __init__(self):
        self.id = None  # type: str
        self.description = None  # type: str
        self.url = None  # type: str
        self.brand = None  # type: Optional[hushh.hcf.Brand.BrandT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        product = Product()
        product.Init(buf, pos)
        return cls.InitFromObj(product)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, product):
        x = ProductT()
        x._UnPack(product)
        return x

    # ProductT
    def _UnPack(self, product):
        if product is None:
            return
        self.id = product.Id()
        self.description = product.Description()
        self.url = product.Url()
        if product.Brand() is not None:
            self.brand = hushh.hcf.Brand.BrandT.InitFromObj(product.Brand())

    # ProductT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.description is not None:
            description = builder.CreateString(self.description)
        if self.url is not None:
            url = builder.CreateString(self.url)
        if self.brand is not None:
            brand = self.brand.Pack(builder)
        ProductStart(builder)
        if self.id is not None:
            ProductAddId(builder, id)
        if self.description is not None:
            ProductAddDescription(builder, description)
        if self.url is not None:
            ProductAddUrl(builder, url)
        if self.brand is not None:
            ProductAddBrand(builder, brand)
        product = ProductEnd(builder)
        return product
