# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hcf

class VibeMode(object):
    """VibeMode.
    """

    ProductText = 0
    ProductImage = 1
    Text = 2
    Image = 3
    Category = 4
