# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hcf

class Vibes(object):
    NONE = 0
    ProductVibes = 1

def VibesCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Vibes().ProductVibes:
        import hushh.hcf.ProductVibes
        return hushh.hcf.ProductVibes.ProductVibesT.InitFromBuf(table.Bytes, table.Pos)
    return None
