# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hcf

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from hushh.hcf.Embedding import Embedding
from typing import Optional
np = import_numpy()

class Vibe(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Vibe()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVibe(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Vibe
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vibe
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Vibe
    def Description(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Vibe
    def ImageBase64(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Vibe
    def Url(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Vibe
    def Embeddings(self, j: int) -> Optional[Embedding]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Embedding()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Vibe
    def EmbeddingsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Vibe
    def EmbeddingsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def VibeStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    VibeStart(builder)

def VibeAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    VibeAddId(builder, id)

def VibeAddDescription(builder: flatbuffers.Builder, description: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def AddDescription(builder: flatbuffers.Builder, description: int):
    VibeAddDescription(builder, description)

def VibeAddImageBase64(builder: flatbuffers.Builder, imageBase64: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(imageBase64), 0)

def AddImageBase64(builder: flatbuffers.Builder, imageBase64: int):
    VibeAddImageBase64(builder, imageBase64)

def VibeAddUrl(builder: flatbuffers.Builder, url: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)

def AddUrl(builder: flatbuffers.Builder, url: int):
    VibeAddUrl(builder, url)

def VibeAddEmbeddings(builder: flatbuffers.Builder, embeddings: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(embeddings), 0)

def AddEmbeddings(builder: flatbuffers.Builder, embeddings: int):
    VibeAddEmbeddings(builder, embeddings)

def VibeStartEmbeddingsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEmbeddingsVector(builder, numElems: int) -> int:
    return VibeStartEmbeddingsVector(builder, numElems)

def VibeEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return VibeEnd(builder)

import hushh.hcf.Embedding
try:
    from typing import List
except:
    pass

class VibeT(object):

    # VibeT
    def __init__(self):
        self.id = None  # type: str
        self.description = None  # type: str
        self.imageBase64 = None  # type: str
        self.url = None  # type: str
        self.embeddings = None  # type: List[hushh.hcf.Embedding.EmbeddingT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vibe = Vibe()
        vibe.Init(buf, pos)
        return cls.InitFromObj(vibe)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, vibe):
        x = VibeT()
        x._UnPack(vibe)
        return x

    # VibeT
    def _UnPack(self, vibe):
        if vibe is None:
            return
        self.id = vibe.Id()
        self.description = vibe.Description()
        self.imageBase64 = vibe.ImageBase64()
        self.url = vibe.Url()
        if not vibe.EmbeddingsIsNone():
            self.embeddings = []
            for i in range(vibe.EmbeddingsLength()):
                if vibe.Embeddings(i) is None:
                    self.embeddings.append(None)
                else:
                    embedding_ = hushh.hcf.Embedding.EmbeddingT.InitFromObj(vibe.Embeddings(i))
                    self.embeddings.append(embedding_)

    # VibeT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.description is not None:
            description = builder.CreateString(self.description)
        if self.imageBase64 is not None:
            imageBase64 = builder.CreateString(self.imageBase64)
        if self.url is not None:
            url = builder.CreateString(self.url)
        if self.embeddings is not None:
            embeddingslist = []
            for i in range(len(self.embeddings)):
                embeddingslist.append(self.embeddings[i].Pack(builder))
            VibeStartEmbeddingsVector(builder, len(self.embeddings))
            for i in reversed(range(len(self.embeddings))):
                builder.PrependUOffsetTRelative(embeddingslist[i])
            embeddings = builder.EndVector()
        VibeStart(builder)
        if self.id is not None:
            VibeAddId(builder, id)
        if self.description is not None:
            VibeAddDescription(builder, description)
        if self.imageBase64 is not None:
            VibeAddImageBase64(builder, imageBase64)
        if self.url is not None:
            VibeAddUrl(builder, url)
        if self.embeddings is not None:
            VibeAddEmbeddings(builder, embeddings)
        vibe = VibeEnd(builder)
        return vibe
