
name: Build

on: [push, pull_request]

permissions:
  contents: write
  id-token: write

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-2019, macOS-11]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install wheel
        run : |
              python -m pip install wheel
              python -m pip install setuptools>64
              python -m pip install build

      - name: Build wheels
        run: python -m build

      - name : Run Tests
        run : |
          python -m pip install ".[ci]"
          make test


      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl

