name: Build

on: [push, pull_request, release]

permissions:
  contents: write
  id-token: write

jobs:
  build_and_test_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-2019, macOS-11]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'


      - name : Run Tests
        run : |
          pip install ".[ci]"
          make test


  release:
    name: Create Github/Pypi Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build_and_test_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Create PyPI release
        uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          build: true

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl
